name: CI/CD Pipeline

on:
  # Uruchamianie po aktualizacji master brancha
  push:
    branches: [ master ]
  
  # Możliwość uruchamiania manualnego
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          # Wyłączam cache npm z powodu problemu z rollup
          # cache: 'npm'
      
      - name: Remove package-lock and node_modules (rollup bug workaround)
        run: |
          rm -rf package-lock.json node_modules
      
      - name: Install dependencies
        run: npm install
      
      - name: Upload node_modules for build job
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: |
            node_modules/
            package-lock.json
          retention-days: 1
      
      - name: Run linting
        run: npm run lint
      
      - name: Check code formatting
        run: npm run format -- --check
      
      - name: Run unit tests
        run: npm run test:run

  build:
    name: Production Build
    runs-on: ubuntu-latest
    needs: test
    
    env:
      NODE_ENV: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      
      - name: Download node_modules from test job
        uses: actions/download-artifact@v4
        with:
          name: node-modules
      
      - name: Make node_modules executable
        run: chmod +x node_modules/.bin/*
      
      - name: Build for production
        run: |
          export PATH="$PWD/node_modules/.bin:$PATH"
          npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 7 