name: CI/CD Pipeline

on:
  # Uruchamianie po aktualizacji master brancha
  push:
    branches: [ master ]
  
  # Możliwość uruchamiania manualnego
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Rebuild native dependencies
        run: npm rebuild
      
      - name: Run linting
        run: npm run lint
      
      - name: Check code formatting
        run: npm run format -- --check
      
      - name: Run unit tests
        run: npm run test:run
      
      - name: Run TypeScript check
        run: npx astro check

  build:
    name: Production Build
    runs-on: ubuntu-latest
    needs: test
    
    env:
      NODE_ENV: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Rebuild native dependencies
        run: npm rebuild
      
      - name: Build for production
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/
          retention-days: 7 